FRW-9206: remove debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -819,7 +819,7 @@ jobs:
 
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_b2b -v glue_env:http://glue.eur.spryker.local -v docker:True --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b .
+                    docker/sdk exec robot-framework robot -v env:api_b2b -v glue_env:http://glue.eu.spryker.local -v docker:True --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b .
 
             -   name: Upload artifacts
                 if: failure()
@@ -866,7 +866,7 @@ jobs:
 
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_b2b -v db_engine:psycopg2 -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b .
+                    docker/sdk exec robot-framework robot -v env:api_b2b -v db_engine:psycopg2 -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b .
 
             -   name: Upload artifacts
                 if: failure()
@@ -905,7 +905,7 @@ jobs:
                     docker/sdk console queue:worker:start --stop-when-empty
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_b2b -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b .
+                    docker/sdk exec robot-framework robot -v env:api_b2b -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b .
             -   name: Upload artifacts
                 if: failure()
                 run: |
@@ -950,7 +950,7 @@ jobs:
                 run: |
                     docker/sdk exec cypress-tests cp .env.example .env
                     for i in 1 2; do
-                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2brrr" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
+                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2b" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
                       sleep 1
                     done
                     (exit $s)
@@ -1000,7 +1000,7 @@ jobs:
                 run: |
                     docker/sdk exec cypress-tests cp .env.dynamic-store.example .env
                     for i in 1 2; do
-                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2brrr" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
+                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2b" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
                       sleep 1
                     done
                     (exit $s)
@@ -1048,7 +1048,7 @@ jobs:
                     docker/sdk console queue:worker:start --stop-when-empty
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_b2b -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b.'*'.positive .
+                    docker/sdk exec robot-framework robot -v env:api_b2b -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b.'*'.positive .
             -   name: Upload artifacts
                 if: failure()
                 run: |
@@ -1093,7 +1093,7 @@ jobs:
                   docker/sdk console queue:worker:start --stop-when-empty
             - name: Run Tests
               run: |
-                  docker/sdk exec robot-framework robot -v env:api_b2b -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b.'*'.negative .
+                  docker/sdk exec robot-framework robot -v env:api_b2b -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.b2b.'*'.negative .
             - name: Upload artifacts
               if: failure()
               run: |
